language: php
php:
  - '7.0'
  - nightly

script: phpunit --verbose .
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_5e7c56201796_key -iv $encrypted_5e7c56201796_iv
  -in deploy_rsa.enc -out ~\/deploy_rsa -d
