language: php
php:
  - '7.0'
  - nightly

script: phpunit --verbose .
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_5e7c56201796_key -iv $encrypted_5e7c56201796_iv
  -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts: $DEPLOYHOST
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $SSHUSER@$DEPLOYHOST:$DEPLOYPATH
  on:
  branch: master